os:
  - linux
  - osx
dist: xenial
osx_image: xcode10.1
language: node_js
  - 10
cache:
  - apt: true
  - directories:
      - node_modules
      - $HOME/.electron
addons:
  apt:
    packages: zip
  homebrew:
    packages: zip
install:
  - npm install
  - npm update
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run build-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run build-darwin; fi
after_success: bash pack.sh
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "./build/packed/*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    branch: master
    tags: true
    all_branches: true
