os:
  - linux
  - osx
dist: xenial
osx_image: xcode10.1
language: node_js
  - 10
cache:
  - apt: true
  - yarn: true
  - directories:
      - node_modules
      - $HOME/.electron
addons:
  apt:
    packages: zip
  homebrew:
    packages: zip
before_install:
  - nvm install 10
  - npm install -g yarn
install:
  - yarn
script:
  - yarn dist
